###GET home
GET http://localhost:3000 HTTP/1.1

###POST reg
POST http://localhost:3000/reg HTTP/1.1
Content-Type: application/json

{
    "name": "Erik",
    "pass": "alma",
    "email": "erik@erik.hu",
    "key": "ZsalmA"
}

###POST login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "erik@erik.hu",
    "pass": "almaaa"
}